---
- hosts: '{{ deploy_host }}'
  become: true
  become_user: devops
  vars:
    ansible_python_interpreter: /usr/bin/python3
    RELEASE_VERSION: v1p.0.48
    ENV_CODE: prod 
  vars_prompt:
    - name: deploy_host
      prompt: "Target Host Name"
      private: no



  roles: 
    - { role: ../roles/deploy-api-artifact-prod }
    





